### ISSUE TITLE
‌‌‌‌‌‌‌About the conversion from className to style

### ISSUE THREAD

**Issue by BANG88** [nativewind/nativewind#1043]
May I ask ‌‌‌when building for production  will className be converted to style? See the image below.

<img width="1955" alt="image" src="https://github.com/user-attachments/assets/8cdc1c42-8d79-43da-a664-7205f3b72c0e">

**Comment by BANG88** [comment]
Create app:

`npx create-expo-stack@latest my-app --nativewindui --drawer+tabs --bun`


Test:
`EXPO_UNSTABLE_ATLAS=true npx expo export -p ios --no-bytecode`

**Comment by danstepanov** [comment]
Classname is always mapped to styles, regardless. Not sure what your issue is based on details provided. 

If you are running into an issue, please provide a reproduction of the issue using one of the following templates:

**StackBlitz template**: https://stackblitz.com/edit/nativewind-test?view=editor
**Create Expo Stack template**:
`npx create-expo-stack@latest --nativewind`
`npx create-expo-stack@latest --nativewind --expo-router`

Closing this issue until these points are addressed

**Comment by marklawlor** [comment]
You can inspect the styles in Orbit as they are generated at build time.

The output file for iOS is `node_modules/react-native-css-interop/.cache/ios.js`. If your running locally this link may work for you `http://localhost:3000/_expo/atlas/2/modules/node_modules%2Freact-native-css-interop%2F.cache%2Fios.js`

**Comment by evelant** [comment]
@marklawlor I was doing some profiling of a release build and noticed that `react-native-css-interop/.cache/android.js` is _huge_. It's a 4.3mb minified js file and it adds ~250ms to app load time just by being included. Is that expected behavior?

**Comment by evelant** [comment]
added a new issue about this here: https://github.com/nativewind/nativewind/issues/1071
