### ISSUE TITLE
Don't change tsconfig.json if `**/*.d.ts` is there already

### ISSUE THREAD

**Issue by pvinis** [nativewind/nativewind#1060]
**Describe the bug**
nativewind is messing with my tsconfig.json to include the d.ts file, but I already have it included because of `**/*.d.ts`.

**Expected behavior**
It should only add it if I dont have the glob there.

**Additional context**
nativewind 4.1.7

**Comment by marklawlor** [comment]
NativeWind matches the behaviour of the major frameworks (Expo, NextJS, Svelte, etc).

From a maintainers perspective, types are illogically annoying. Inexperienced users change this field because they are "trying to get the types working". If NativeWind is inserting/removing a field as they are doing this it further annoys the user. People also forget what the glob is including. So if Typescript is slowing down vscode people again play with this field trying to fix the problem. 

The solution to this is just be explicit. People know that this line supplies the types for that library/framework so they leave that line alone. It's a bit silly but it works.

Also, I would not use `**/*.d.ts` and would consider that a problem that could introduce false positives into your code. The `types` field in `package.json` can be conditional, exposing different types for different import conditions / sub paths. With that glob, you are overriding a package authors intentions and include all types. For example you can use the `react-native` attribute to have different types if the user is using React Native (Metro) as opposed to a different bundler. Your glob would include both versions.
