### ISSUE TITLE
[v4] Allow compiling third party modules

### ISSUE THREAD

**Issue by slavagoreev** [nativewind/nativewind#1103]
**Describe the bug**
I am struggling to make primitives from `react native reusables` to work in a web invironment. Native components from like `View` or `Text` work perfectly fine but custom components do not work without wrapping all of the imports in `cssInterop` function which is not really good. I've tried to monkey-patch a babel/preset to include some of `node_modules` but haven't succeeded. Native works fine but custom web (NextJs) isn't.

```tsx
const AvatarPrimitiveRoot = cssInterop(AvatarPrimitive.Root, {
  className: 'style'
});
const AvatarPrimitiveImage = cssInterop(AvatarPrimitive.Image, {
  className: 'style'
});
const AvatarPrimitiveFallback = cssInterop(AvatarPrimitive.Fallback, {
  className: 'style'
});
```

**Expected behavior**
Please, make it possible to compile additional modules like is was made in v2.

**Comment by marklawlor** [comment]
This is expected behaviour and is not going to change.

`react-native-reusables` appears to be be build on-top of the normal `View`/`Text` components, so it must not be passing down props correctly.

For example this component is "cherry-picking" its props.

```
function MyView({ children }: ViewProps {
  return <View>{children}</View>
}
```

Instead it should pass them down to the view

```
function MyView({ children, ...props }: ViewProps {
  return <View {...props}>{children}</View>
}
```

I would recommend opening a PR with the library to make compatible with NativeWind.

**Comment by mrzachnugent** [comment]
@marklawlor I can confirm that all `@rn-primitives` component props are passed as you are showing in the second code snippet and it is using `React.forwardRef` to forward the ref as well.

Here is a repo that demonstrates that when the `@rn-primitives` come from `node_modules`, the styling cannot be applied with class names. However, if I copy the component code and paste it into the nextjs project, it works. https://github.com/mrzachnugent/nextjs-nativewind-rn-primitives-repro

**Comment by slavagoreev** [comment]
@marklawlor may we reopen the issue? Now we've got a repro thanks to @mrzachnugent and you could investigate the problem easier

**Comment by marklawlor** [comment]
`@rn-primatives` is published to `npm` as a compiled package, which normally should be fine but it is compiling with `jsx: 'react'`. The recommended setting is`jsx: 'react-native'` ([reference](https://github.com/tsconfig/bases/blob/main/bases/react-native.json)).

NativeWind has a Babel plugin to experimentally work around this (add `nativewind/babel` as a plugin), but NextJS no longer uses Babel to transform its code.

So either `@rn-primatives` should update its build step to use the recommend settings for React Native or someone needs to port the Babel plugin to NextJS.

**Comment by mrzachnugent** [comment]
@marklawlor Thanks you! I will make those changes.

**Comment by mrzachnugent** [comment]
@marklawlor Unfortunately after applying your suggestions, I couldn't get it to work. 

I made a Draft PR with a new branch in rn-primitives to attempt to fix it (https://github.com/roninoss/rn-primitives/pull/37) if ever you want to check it out. I updated the README's instructions for getting started.

**Comment by marklawlor** [comment]
Is your NextJS project is setting `jsxImportSource: 'nativewind'`?

**Comment by mrzachnugent** [comment]
@marklawlor Yes, it is.

![Screenshot 2024-10-08 at 5 18 48 PM](https://github.com/user-attachments/assets/5e32e64c-9ca0-44b9-9229-4f8e4ed4744d)

**Comment by marklawlor** [comment]
I do not understand how to reproduce the issue, the styles are working in the web environment. Steps I followed:

* Cloned repo
* Switched to `@zach/feat-nextjs` branch
* `pnpm install`
* `pnpm build`
* `pnpm dev:nextjs-nativewind`

Is this possibly an issue with TurboRepo caching on your end? Or am I misunderstanding the issue?

**Comment by mrzachnugent** [comment]
@marklawlor Sorry, I didn't explain it properly for this repo. NativeWind works with elements imported from "react-native" but in my case doesn't work for the `@rn-primitives/avatar` package that comes from npm and it made of react-native components such as View, Pressable, Text, and Image.

The button is made up of a Pressable and a Text component imported from "react-native" and that works. The issue is with the components from `import * as AvatarPrimitive from '@rn-primitives/avatar';` in `apps/nextjs-nativewind/src/components/ui/avatar.tsx`. In this file, I am adding classNames to `AvatarPrimitiveRoot` (a `View`) under the hood, `AvatarPrimitiveImage` (an `Image`), and `AvatarPrimitiveFallback` (a View) but the styles are not showing up. This primitive works and is styled with NativeWind on iOS, Android, and expo-web but I cannot get it to work with Nextjs.

For context, here is the same component in an expo-web deployed application: https://rnr-showcase.vercel.app/avatar

**Comment by marklawlor** [comment]
@mrzachnugent If you open the DevTools and look at the source code for `packages/avatar/dist/avatar.js` (make sure you are looking at the original file and not the source mapped version), you can see that it is still compiled as `React.createElement` and not using the jsx transformation.

**Comment by marklawlor** [comment]
If I modify `packages/avatar/tsup.config.ts` to preserve the JSX, the `<Avatar />` styles load correctly.

```diff
import { defineConfig, Options } from 'tsup';

export default defineConfig((options: Options) => ({
  entry: ['src/index.ts', 'src/avatar.tsx'],
  banner: {
    js: "'use client'",
  },
  clean: true,
  format: ['cjs', 'esm'],
  external: ['react', './avatar'],
  dts: true,
  ...options,
+ esbuildOptions(options) {
+   options.jsx = 'preserve';
+ },
}));

**Comment by mrzachnugent** [comment]
@marklawlor Thank you so much! That was it. Really appreciate you looking into it.

@slavagoreev You can install the latest versions of the primitives for it to work with nextjs, without the need to use `cssInterop`. Here's a live demo of all the primitives: https://nextjs-nativewind-rn-primitives-repro.vercel.app/
