### ISSUE TITLE
How to generate pre-compiled RN StyleSheet objects in V3?

### ISSUE THREAD

**Issue by fendyk** [nativewind/nativewind#374]
**Describe the bug**
I am trying to generate pre-compiled RN StyleSheet objects in V3, but since postcss is no longer supported, I cannot find a way to do this.

**To Reproduce**
N/A

**Expected behavior**
Output a output file with pre compiled components.

**Expo Snack**
N/A

**Screenshots**
N/A

**Additional context**
Would like to know a solution for this, also, would be nice if you could --watch the output aswell.

**Comment by jgornick** [comment]
If I'm understanding this correctly, this means taking a file like:

```js
// src/styles.js

const Styles = ['m-0', 'm-100']
```

... and transform into:

```js
// dist/styles.js

const { NativeWindStyleSheet } = require('nativewind')

const Styles = ['w-auto', 'h-auto']

NativeWindStyleSheet.create({
    "m-0": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "m-100": {
      "marginTop": 8,
      "marginRight": 8,
      "marginBottom": 8,
      "marginLeft": 8
    },
})
```

If so, yes this doesn't seem to be capable anymore with just the babel plugin/preset in V3. 

@marklawlor Without using metro is there a way to just transform JS to append the compiled stylesheet?

**Comment by jgornick** [comment]
For what it's worth, I was able to generate a stylesheet borrowing the code from the [metro tailwind script](https://github.com/marklawlor/nativewind/blob/next/packages/nativewind/src/metro/tailwind.ts). 

It would be nice if this functionality was provided in the babel plugin, even if it was optionally flagged. 

@marklawlor I'm assuming there is a reason, but curious why this functionality was removed from the babel plugin?

**Comment by marklawlor** [comment]
I'm still looking for better ways to manage this and make it work with tools like Turbopack. I haven't added it just because it was low on the priority list.

I'm struggling to understand why people want this feature. It seems a lot of people want it for library development, but by precompiling styles your denying the ability for users to customise styles. If your styles are immutable, then NativeWind is just bloat and unneeded.

Can you please describe your use-case so I can understand this better?

If you are writing a component library, I am current working on a new styling library which will give you the power of NativeWind, without the overhead.

**Comment by scott-harrison** [comment]
I have a similar issue. Been trying to create a component library that can be used by multiple projects.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
