### ISSUE TITLE
v4 - 3rd party module has to be remapped

### ISSUE THREAD

**Issue by luixo** [nativewind/nativewind#693]
**Describe the bug**
In instruction there is a description of how to make 3rd party library components use className and it states that nativewind does make a default compilation of `className` -> `style`.
Unfortunately, this doesn't work with a pretty simple example of `@expo/html-elements`.
I have to add `remapProps(H1, { className: "style" })` (and so on for each component I use) for `className` to get through.

**To Reproduce**
1. Add `H1` from `@expo/html-elements` in nativewind project
2. Witness `className` not being passed through
3. Add `remapProps(H1, { className: "style" })` in the code
4. Witness `className` being passed through

**Expected behavior**
Elements that wrap `Text` / `View` should work out of the box or this caveat should be stated explicitely in the docs

**Expo Snack**
No snacks for v4 yet

**Screenshots**
-

**Additional context**
I did a little research to catch that out and I found that in a tree of components there is a depth limit with which css-interop function (called `jsxDEV` in dev) is being rendered and the last one is `H1` though internally it has `Text` that is being rendered inside of it.
I suspect that runtime can only run on project files, but cannot get through to node_modules, though I might be wrong on that.

**Comment by tyrauber** [comment]
I struggled with the same issue and after some investigation discovered that this issue primarily affects the header elements.  **remapProps is not required**.  Text elements like B, P, etc, work just fine.

The issue is: Elements with a pre-defined style, the defined style take precedences over className defined styles. 

For example, [header style properties](https://github.com/expo/expo/blob/main/packages/html-elements/build/elements/Headings.js#L35-L77) fontSize and fontWeight.

Doesn't work: `<H1 className="text-8xl extrabold  text-black">H1 Header</H1>`
Works: `<H1 className="!text-8xl !extrabold text-black">H1 Header</H1>`

**The workaround is to use the important style (!) when overwriting existing styles.**

Note: This issues doesn't impact web, only native devices.
![h1_important](https://github.com/marklawlor/nativewind/assets/109972/bd08f7a3-5e52-4b9a-9cf4-c1e809c2c42e)

**Comment by luixo** [comment]
My problem happens on web and I can see in devtools classNames not being passed.

**Comment by tyrauber** [comment]
Interesting, @luixo, what version are you using? nativewind@4.0.16, @expo/html-elements@0.9.0?

**Comment by patlux** [comment]
v2 also doesn't work.

My workaround:

```tsx
import * as h from '@expo/html-elements'
import { styled } from 'nativewind'

export const A = styled(h.A)
export const Article = styled(h.Article)
export const Aside = styled(h.Aside)
export const B = styled(h.B)
export const Blockquote = styled(h.BlockQuote)
export const BR = styled(h.BR)
export const Caption = styled(h.Caption)
export const Code = styled(h.Code)
export const Del = styled(h.Del)
export const Div = styled(h.Div)
export const EM = styled(h.EM)
export const Footer = styled(h.Footer)
export const H1 = styled(h.H1)
export const H2 = styled(h.H2)
export const H3 = styled(h.H3)
export const H4 = styled(h.H4)
export const H5 = styled(h.H5)
export const Header = styled(h.Header)
export const HR = styled(h.HR)
export const I = styled(h.I)
export const Main = styled(h.Main)
export const Mark = styled(h.Mark)
export const Nav = styled(h.Nav)
export const P = styled(h.P)
export const Pre = styled(h.Pre)
export const Q = styled(h.Q)
export const S = styled(h.S)
export const Section = styled(h.Section)
export const Span = styled(h.Span)
export const Strong = styled(h.Strong)
export const Table = styled(h.Table)
export const TBody = styled(h.TBody)
export const TD = styled(h.TD)
export const TFoot = styled(h.TFoot)
export const TH = styled(h.TH)
export const THead = styled(h.THead)
export const Time = styled(h.Time)
export const TR = styled(h.TR)
export const UL = styled(h.UL)
export const LI = styled(h.LI)
```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
