### ISSUE TITLE
[v4] Error when using React Server Components with Next.js

### ISSUE THREAD

**Issue by JWesorick** [nativewind/nativewind#772]
**Describe the bug**
In a NextJS 14 site using app directory and following the [NextJS setup instructions](https://www.nativewind.dev/v4/getting-started/nextjs) I get the following errors:

```
Attempted import error: 'jsxDEV' is not exported from 'nativewind/jsx-dev-runtime' (imported as '_jsxDEV').
```

```
 ⨯ ../node_modules/react-native-web/dist/modules/useLocale/index.js (16:47) @ defaultLocale
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
```

The step for adding `"jsxImportSource": "nativewind"` seems to be where everything goes wrong. Removing that allows the page to load fine, just no styles.

This is also in a [Solito v4 monorepo](https://github.com/nandorojo/solito)

**Additional context**
```
nativewind@npm:4.0.23 [f87a9]
solito@npm:4.2.0
next@npm:14.0.4 [d369e]
react@npm:18.2.0
react-native@npm:0.72.6 [d369e]
react-native-web@npm:0.19.9 [d369e]
```

Maybe be helpful:
- https://github.com/vercel/next.js/issues/41994

**Comment by JWesorick** [comment]
My workaround for now:

- I upgraded to next@npm:14.1.0 [d369e]
- Added `/** @jsxImportSource react */` to the top of my server components ('layout.tsx, page.tsx'). Styling still seems to work just fine in those components.

**Comment by JWesorick** [comment]
Seems like all the tailwind classes are there from the beginning of the page load but additional inline styles (I think added by react-native) pop in late client side making the page load look jank.

**Comment by panzacoder** [comment]
@JWesorick I'm trying to find a way around adding `@jsxImportSource react` to every one of my server components. It's not a *huge* deal, but I feel like in a monorepo, I should be able to define import sources separately for my next app vs my local package that has my universal/nativewind code. Anything in the next app should just be plain tailwind.

That said, I know there is some transpiling magic happening here, is this something worth looking into @marklawlor or does it seem antithetical to your approach?

**Comment by iamursky** [comment]
Having the same issue in usual Next.js project, not a monorepo.

**Comment by panzacoder** [comment]
@JWesorick Have you figured out a solution to the pop-in? I'm trying not to focus on it but I the pop-in is so pronounced in dev 😂

**Comment by panzacoder** [comment]
I fixed the pop-in issue! 🎉

For me, it's actually symptom of the `@expo/next-adapter` not nativewind.

I found the solution in the [Solito repo](https://github.com/nandorojo/solito/blob/master/develop/appdir/app/styles-provider.tsx)

Basically, just add this Provider to your app, and pop-in is gone.

It's actually not the tailwind styles that are popping in, it's the inline RN stylesheet popping in after. I noticed because it was only stuff like line-breaks that weren't working.

```javascript
// @ts-nocheck
'use client'
import { useServerInsertedHTML } from 'next/navigation'
import { StyleSheet } from 'react-native'

export function StylesProvider({ children }: { children: React.ReactNode }) {
  useServerInsertedHTML(() => {
    const sheet = StyleSheet.getSheet()
    return (
      <style
        dangerouslySetInnerHTML={{ __html: sheet.textContent }}
        id={sheet.id}
      />
    )
  })
  return <>{children}</>
}
```

I may come back to this at another time and try to figure out how to get this working in a server component, but all good for now!

**Comment by panzacoder** [comment]
I would also still like to figure out how to remove the `/* jsxImportSource react*/` from every route, but not there yet.

**Comment by JWesorick** [comment]
@panzacoder Still no real fix for the pop in. I was able to fix it enough by just adding css rules for my specifc page.

**Comment by panzacoder** [comment]
@JWesorick Did you try the provider solution I added above? The stylesheet is getting loaded client-side if you don't explicitly wrap your code with it.

**Comment by panzacoder** [comment]
@shawnmclean Definitely not perfect, but this project I am working on has it working: https://github.com/panzacoder/fcc-monorepo

**Comment by panzacoder** [comment]
@shawnmclean Hmm, two things you might look into from 10m poking at it:

1. I had to add `/** @jsxImportSource react */` to the top of _every_ server component in my repo, so that could be part of your issue, but that didn't solve anything for me immediately.
2. You are using React 19 RC and Next 15 RC, as well as running your dev server with `--turbo` (turbopack instead of webpack). All of that stuff is still experimental and any of them could have impact on the whole react-native-web/nativewind world, since all of that happens in the transpile step.

I would suggest trying to downgrade everything to the latest stable version, or cut a fresh repo based on an earlier starter.


Biggest difference I've found in react-web vs react-native: the latest versions of things nearly always break crap on native, and I am probably not smart enough / don't have enough time to fix those broken things. Sometimes you really have to pick your battles with what is worth the time.

**Comment by oneilsoftware-brandonmiller** [comment]
@panzacoder thank you so much i was able to fix my issue with your solution. 
I have created an example repo that is very bare bones for anyone wanting to clone or fork that has just expo next and nativewind in it. https://github.com/oneilsoftware-brandonmiller/Template-Expo-Next-Nativewind-With-SSR. this is using your solution. thanks again you save us a massive rewrite of our code base

**Comment by panzacoder** [comment]
@oneilsoftware-brandonmiller glad I could help! I do freelance as well if you're ever in need of some help, HMU! 😂

**Comment by wingy3181** [comment]
@oneilsoftware-brandonmiller isn't your example really a client component?

**Comment by oneilsoftware-brandonmiller** [comment]
It uses clients to render yes but is set up where the page.tsx is server rendered, for api calls and the like and imports a client component to render that information. diff between using the app dir and the pages dir.  where you can pass in client components too it

**Comment by oneilsoftware-brandonmiller** [comment]
> @oneilsoftware-brandonmiller isn't your example really a client component?


It uses clients to render yes but is set up where the page.tsx is server rendered, for api calls and the like and imports a client component to render that information. diff between using the app dir and the pages dir. where you can pass in client components too it

its ment to be bear bones and have one file (pages.tsx) for SRR and one for client rendering nothing fancy it was for me to test the solution earlier as stripped down as posible.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
